version: "3.8"

volumes:
  mariadb:
    driver: local

networks:
    db:
        driver: bridge

services:
  mysql:
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lectures
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    command: ['mysqld', '--default-authentication-plugin=mysql_native_password']
    expose:
        - "40000"
    ports:
        - "40000:3306"
    volumes:
     - mariadb:/var/lib/mysql
    networks:
      db:

  phpmyadmin:
    image: phpmyadmin
    restart: on-failure
    expose:
      - "40001"
    ports:
      - "40001:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    networks:
      db: